name: CICD
on: push

jobs:
  compile:
    runs-on: linux-latest
    steps:
    - name: test message print
      run: sudo echo "Hello linux"


  job-2:
    runs-on: ubuntu-latest
    steps: 
    - name: test ubuntu
      run: sudo echo "hi ubuntu"


